{
 "title": "NiFi Dashboard With Cluster And Instance",
 "description": "A complete dashboard for all metrics exposed using PrometheusReportingTask With Cluster And Instance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(nifi_amount_bytes_read,cluster)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nifi_amount_bytes_read{cluster=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nifi_jvm_uptime{instance=\"$instance\",cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "JVM Heap Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "nifi_jvm_heap_usage{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "JVM Heap Used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "nifi_jvm_heap_used{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "JVM Daemon Thread Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nifi_jvm_daemon_thread_count{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "JVM Heap Non Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "nifi_jvm_heap_non_usage{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "JVM GC Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "nifi_jvm_gc_time{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{gc_name}}"
      }
     ]
    },
    {
     "title": "JVM GC Runs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nifi_jvm_gc_runs{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": " {{gc_name}}"
      }
     ]
    },
    {
     "title": "JVM File Descriptor Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nifi_jvm_file_descriptor_usage{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "JVM Thread Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nifi_jvm_thread_count{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": " "
      }
     ]
    }
   ]
  },
  {
   "title": "Processors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Lineage Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "nifi_average_lineage_duration{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Terminated Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_threads_terminated{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Active Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_threads_active{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FlowFiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received FlowFiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_flowfiles_received{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Transferred FlowFiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_flowfiles_transferred{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Sent FlowFiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_flowfiles_sent{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Removed FlowFiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_flowfiles_removed{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Items",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input Items",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_items_input{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}} {{component_id}}"
      }
     ]
    },
    {
     "title": "Output Items",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_items_output{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}} {{component_id}}"
      }
     ]
    },
    {
     "title": "Queued Items",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_items_queued{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}} {{component_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Contents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Input Content",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "nifi_size_content_input_total{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Total Output Content",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "nifi_size_content_output_total{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Total Queued Content",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "nifi_size_content_queued_total{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backpressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backpressure Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "nifi_backpressure_bytes_threshold{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}} {{source_name}}"
      }
     ]
    },
    {
     "title": "Backpressure Objects",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_backpressure_object_threshold{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}} {{source_name}}"
      }
     ]
    },
    {
     "title": "Backpressure Enabled",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_backpressure_enabled{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}} {{source_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transferred Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_bytes_transferred{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Received Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_bytes_received{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Written Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_bytes_written{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Sent Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_bytes_sent{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Read Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_bytes_read{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    }
   ]
  },
  { "title": "System & Repositories", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "FlowFile Repository Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nifi_flowfile_repo_free_space_bytes{instance=\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "Free Space"
    },
    {
     "expr": "nifi_flowfile_repo_used_space_bytes{instance=\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "Used Space"
    },
    {
     "expr": "nifi_flowfile_repo_total_space_bytes{instance=\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "Total Capacity"
    }
   ]
  },
  {
   "title": "Content Repository Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nifi_content_repo_free_space_bytes{instance=\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "Free Space"
    },
    {
     "expr": "nifi_content_repo_used_space_bytes{instance=\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "Used Space"
    },
    {
     "expr": "nifi_content_repo_total_space_bytes{instance=\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "Total Capacity"
    }
   ]
  },
  {
   "title": "Provenance Repository Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nifi_provenance_repo_free_space_bytes{instance=\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "Free Space"
    },
    {
     "expr": "nifi_provenance_repo_used_space_bytes{instance=\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "Used Space"
    },
    {
     "expr": "nifi_provenance_repo_total_space_bytes{instance=\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "Total Capacity"
    }
   ]
  },
  { "title": "Processing Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Processing CPU Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(nifi_processing_performance_cpu_duration{instance=\"$instance\",cluster=\"$cluster\"}[5m])",
     "legendFormat": "CPU Duration Rate"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(gc__duration{instance=\"$instance\",cluster=\"$cluster\"}[5m])",
     "legendFormat": "GC Duration Rate"
    }
   ]
  },
  {
   "title": "Session Commit Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(session_commit_duration{instance=\"$instance\",cluster=\"$cluster\"}[5m])",
     "legendFormat": "Session Commit Rate"
    }
   ]
  }
 ]
}