-- Копируй весь результат и сохрани в файл export_revolute.txt
WITH user_roles AS (
    SELECT DISTINCT ROLE_NAME FROM "PUBLIC"."EFFECTIVE_ROLES" WHERE USER_NAME = 'REVOLUTE'
),
user_privs AS (
    SELECT DISTINCT PRIVILEGE, OBJECT_TYPE, SCHEMA_NAME, OBJECT_NAME, IS_GRANTABLE 
    FROM "PUBLIC"."EFFECTIVE_PRIVILEGES" 
    WHERE USER_NAME = 'REVOLUTE' AND GRANTEE_TYPE = 'USER'
)
-- Создание пользователя
SELECT 'CREATE USER "REVOLUTE" PASSWORD "ChangeMe123" NO FORCE_FIRST_PASSWORD_CHANGE;' AS commands
UNION ALL
-- Роли  
SELECT 'GRANT "' || ROLE_NAME || '" TO "REVOLUTE";' FROM user_roles
UNION ALL
-- Системные привилегии
SELECT 'GRANT ' || PRIVILEGE || ' TO "REVOLUTE"' || CASE WHEN IS_GRANTABLE='TRUE' THEN ' WITH ADMIN OPTION' ELSE '' END || ';'
FROM user_privs WHERE OBJECT_TYPE = 'SYSTEM'
UNION ALL  
-- Схемные привилегии
SELECT 'GRANT ' || PRIVILEGE || ' ON SCHEMA "' || SCHEMA_NAME || '" TO "REVOLUTE"' || CASE WHEN IS_GRANTABLE='TRUE' THEN ' WITH GRANT OPTION' ELSE '' END || ';'
FROM user_privs WHERE OBJECT_TYPE = 'SCHEMA'
UNION ALL
-- Объектные привилегии  
SELECT 'GRANT ' || PRIVILEGE || ' ON "' || SCHEMA_NAME || '"."' || OBJECT_NAME || '" TO "REVOLUTE"' || CASE WHEN IS_GRANTABLE='TRUE' THEN ' WITH GRANT OPTION' ELSE '' END || ';'
FROM user_privs WHERE OBJECT_TYPE IN ('TABLE','VIEW','PROCEDURE','FUNCTION')
ORDER BY commands;
